# Generated by Django 4.1.2 on 2022-10-19 08:48

from django.db import migrations
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL([("INSERT INTO public.auth_user (password, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES (%s, true, %s, '', '', '', true, true, NOW());", [make_password('coderpad'), 'admin'])])
    ]
