# Generated by Django 4.1.2 on 2024-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.TextField(default='Active'),
        ),
    ]
